# Задание к занятию «Python для анализа данных: numpy и scipy»

In [1]:
import numpy as np
import pandas as pd

## Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
N = 10 # Задаем начальные параметры
np.flip(np.arange(N))

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = 10 # Задаем начальные параметры
mtrx = np.diag(np.flip(np.arange(N)), k=0) # Создаем диагональную матрицу от N до 0
mtrx

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
sum(np.diag(mtrx)) # Сумма значений по диагонали

45

## Задание 3

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [5]:
# Грузим датасет с рейтинами, чтобы по ним найти movieid которому было больше всего
# выставлено оценок 5.0
ratings_df = pd.read_csv('./ml-latest-small/ratings.csv')
ratings_df.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [6]:
# считаем какому movieId было проставлено больше всех 5.0
most_rating_movieid = ratings_df[ratings_df.rating == 5
].groupby('movieId')['rating'].count().idxmax(axis = 0) 

In [7]:
# Грузим датасет с фильмами (для того чтобы по movieid найти название фильма)
movie_df = pd.read_csv('./ml-latest-small/movies.csv')
movie_df.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [8]:
# Находим название фильма с таким movieid
movie_df[movie_df.movieId == most_rating_movieid]

movieId                             title       genres
284      318  Shawshank Redemption, The (1994)  Crime|Drama

## Задание 4

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [9]:
# Грузим дата сет с потреблением
power_df = pd.read_csv('./power.csv')
power_df.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [10]:
# Cуммарное потребление стран Прибалтики (Латвия, Литва и Эстония) 
power_df[
    ((power_df.country == 'Latvia') |
    (power_df.country == 'Estonia') |
    (power_df.country == 'Lithuania'))
    &
    ((power_df.category == 4) | 
    (power_df.category == 12) | 
    (power_df.category == 21))
    &
    (power_df.quantity > 0)
]['quantity'].sum()

970728.0

## Задание 5
Решите систему уравнений:

```
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
```

In [11]:
# Импортируем вспомогательную библиотеку
from numpy import linalg

In [12]:
# Матрица коэффициентов
mtrx_coef = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

# Матрица свободных значений
mtrx_val = np.array( [4, 12, -3] )

In [13]:
# Решаем линейное уравнение
mtrx_res = linalg.solve(mtrx_coef, mtrx_val)
mtrx_res

array([ 0.46666667,  3.84444444, -5.55555556])

In [14]:
np.allclose( np.dot(mtrx_coef, mtrx_res), mtrx_val ) # Проверка решения

True